export const GET_ERRORS = "GET_ERRORS"
export const SET_CURRENT_USER = "SET_CURRENT_USER"
export const GET_PROFILE = "GET_PROFILE"
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND" // TODO
export const CLEAR_CURRENT_PROFILE = 'CLEAR_CURRENT_PROFILE' // TODO
export const GET_PROFILES = "GET_PROFILES" // TODO
